
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("1.1.0.10")]
 [assembly: AssemblyFileVersion("1.1.0.10")]
 [assembly: KSPAssembly("KSP_PartHighlighter", 1, 1, 0)]